import {FormEvent,useEffect,useMemo,useState} from "react";
import type {Session} from "@supabase/supabase-js";
import {supabase,configured} from "./lib/supabase";
type Lead={id:string;company:string;contact_name:string;stage:string;value:number;neighborhood:string;next_step:string};
const stages=["Prospect","Contacted","Discovery","Proposal","Won"];
const demo:Lead[]=[
{id:"1",company:"Hillcrest Hospitality Group",contact_name:"Alex Rivera",stage:"Discovery",value:4200,neighborhood:"Hillcrest",next_step:"Send visitor profile"},
{id:"2",company:"North Park Social",contact_name:"Jordan Lee",stage:"Proposal",value:6800,neighborhood:"North Park",next_step:"Review sponsorship"},
{id:"3",company:"Liberty Station Events",contact_name:"Morgan Chen",stage:"Contacted",value:3500,neighborhood:"Point Loma",next_step:"Book discovery"}];

function Auth(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[mode,setMode]=useState<"signin"|"signup">("signin");const[msg,setMsg]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setMsg("Working…");const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setMsg(result.error?.message||(mode==="signup"?"Check your email to confirm your account.":"Welcome back."));}
 return <main className="auth"><section className="authCard"><div className="mark">FM</div><p className="eyebrow">SAN DIEGO SALES PILOT</p><h1>Sell with color.<br/>Grow with clarity.</h1><p>A focused, affirming workspace for Fun Maps representatives.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>{mode==="signin"?"Sign in":"Create account"}</button></form><button className="link" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"New here? Create an account":"Already have an account? Sign in"}</button>{msg&&<p>{msg}</p>}</section></main>
}
export default function App(){
 const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[leads,setLeads]=useState<Lead[]>(demo),[view,setView]=useState("Dashboard"),[showAdd,setShowAdd]=useState(false),[coach,setCoach]=useState("You only need one meaningful next action. Which deal deserves it?");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;supabase.from("leads").select("*").order("created_at",{ascending:false}).then(({data})=>{if(data?.length)setLeads(data as Lead[])})},[session]);
 const pipeline=leads.reduce((s,l)=>s+Number(l.value),0),won=leads.filter(l=>l.stage==="Won").length;
 const areas=useMemo(()=>Object.entries(leads.reduce<Record<string,number>>((a,l)=>{a[l.neighborhood]=(a[l.neighborhood]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[leads]);
 async function addLead(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const lead={company:String(f.get("company")),contact_name:String(f.get("contact")),stage:"Prospect",value:Number(f.get("value")),neighborhood:String(f.get("neighborhood")),next_step:"Make first contact"};const{data,error}=await supabase.from("leads").insert(lead).select().single();if(!error)setLeads(x=>[data as Lead,...x]);setShowAdd(false)}
 if(loading)return <div className="loading">Loading your pilot…</div>;
 if(configured&&!session)return <Auth/>;
 return <div className="shell"><aside><div className="logo"><span>FM</span><strong>Fun Maps</strong></div><small>30-day sales pilot</small>{["Dashboard","Pipeline","Hotspots","Activity"].map(n=><button className={view===n?"active":""} onClick={()=>setView(n)} key={n}>{n}</button>)}<button className="reset" onClick={()=>setCoach("Pause for 90 seconds. Water, breathe, then choose one tiny next step.")}>Take a reset</button>{session&&<button onClick={()=>supabase.auth.signOut()}>Sign out</button>}</aside><main className="content"><header><div><p className="eyebrow">WEEK 1 · BUILD THE RHYTHM</p><h1>{view}</h1></div><button className="primary" onClick={()=>setShowAdd(true)}>＋ Add lead</button></header>
 {!configured&&<div className="notice">Preview mode · Connect Supabase in Lovable before publishing.</div>}
 {view==="Dashboard"&&<><section className="coach"><b>✦ Momentum Coach</b><p>{coach}</p><button onClick={()=>setCoach("Follow up with the warmest proposal before starting new outreach.")}>Guide me</button></section><section className="metrics"><Card label="Active leads" value={String(leads.length)} note="Target 12"/><Card label="Pipeline" value={"$"+pipeline.toLocaleString()} note="Across 5 stages"/><Card label="Wins" value={String(won)} note={(leads.length?Math.round(won/leads.length*100):0)+"% conversion"}/><Card label="Weekly target" value={Math.min(100,Math.round(leads.length/12*100))+"%"} note={leads.length+"/12 leads"}/></section><section className="two"><article className="panel"><h2>Today’s three</h2>{leads.slice(0,3).map(l=><div className="task" key={l.id}><i/><span><b>{l.company}</b><small>{l.next_step}</small></span></div>)}</article><article className="panel"><h2>Pipeline health</h2>{stages.map(s=><div className="bar" key={s}><span>{s}</span><i><b style={{width:Math.max(8,leads.filter(l=>l.stage===s).length/leads.length*100)+"%"}}/></i><em>{leads.filter(l=>l.stage===s).length}</em></div>)}</article></section></>}
 {view==="Pipeline"&&<section className="board">{stages.map(stage=><div className="column" key={stage}><h3>{stage} <span>{leads.filter(l=>l.stage===stage).length}</span></h3>{leads.filter(l=>l.stage===stage).map(l=><article className="deal" key={l.id}><b>{l.company}</b><span>{l.contact_name}</span><strong>{"$"+l.value.toLocaleString()}</strong><small>{l.next_step}</small></article>)}</div>)}</section>}
 {view==="Hotspots"&&<section className="two"><article className="panel map"><i/><i/><i/><b>San Diego opportunity map</b></article><article className="panel"><h2>Visitor opportunity signals</h2>{areas.map(([n,c],i)=><div className="area" key={n}><b>{i+1}</b><span>{n}</span><strong>{c} leads</strong></div>)}<p className="muted">Connect a privacy-safe visitor analytics source to replace pilot data.</p></article></section>}
 {view==="Activity"&&<section className="panel"><h2>Accountability rhythm</h2>{["10 focused outreaches","3 follow-ups","2 discovery conversations","1 proposal advanced","Friday learning review"].map((x,i)=><label className="check" key={x}><input type="checkbox"/><span>{x}</span><em>{i<2?"Today":"This week"}</em></label>)}</section>}
 </main>{showAdd&&<div className="modal"><form onSubmit={addLead}><h2>Add a lead</h2><label>Business<input name="company" required/></label><label>Contact<input name="contact" required/></label><label>Potential value<input name="value" type="number" min="0" required/></label><label>Neighborhood<input name="neighborhood" required/></label><div><button type="button" onClick={()=>setShowAdd(false)}>Cancel</button><button className="primary">Save lead</button></div></form></div>}</div>
}
function Card({label,value,note}:{label:string,value:string,note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
